modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "spritearrows"
version = "${version}"
displayName = "Sprite Arrows"
authors = "agnor99"
description = '''
Render arrows as their item model. Did you know that tridents are arrows?
'''
logoFile = "assets/spritearrows/icon.png"

[[dependencies.spritearrows]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.spritearrows]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2]"
ordering = "NONE"
side = "CLIENT"