modLoader = "javafml"
loaderVersion = "[45,)"
issueTrackerURL = "https://github.com/agnor99/arrow-sprites/issues"
license = "MIT"

[[mods]]
modId = "spritearrows"
version = "${version}"
displayName = "Sprite Arrows"
authors = "agnor99"
description = '''
Render arrows as their item model. Did you know that tridents are arrows?
'''
logoFile = "assets/spritearrows/icon.png"

[[dependencies.spritearrows]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.spritearrows]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "CLIENT"